apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: devops
    app.kubernetes.io/instance: devops-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  name: devops
spec:
  selector:
    app: devops
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 5000
